### ISSUE TITLE
What if the data set is not in order

### ISSUE THREAD

**Issue by blacksag** [piyushvaishya/My-ML-Practice#1]
## e.g. i have changed some input myself:
![capture](https://user-images.githubusercontent.com/36514625/50998291-f5614080-154c-11e9-8e0c-708a55c6df15.JPG)
![capture2](https://user-images.githubusercontent.com/36514625/50998296-fabe8b00-154c-11e9-8742-09de31aaea41.JPG)

Please correct me if i have understood the assignment wrong!

**Comment by piyushvaishya** [comment]
Yes, you are right.
I have corrected it.
